/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yc_jnibase_JniClient */

#ifndef _Included_com_yc_jnibase_JniClient
#define _Included_com_yc_jnibase_JniClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yc_jnibase_JniClient
 * Method:    JavaCallCForString
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_yc_jnibase_JniClient_JavaCallCForString
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_yc_jnibase_JniClient
 * Method:    JavaCallCForInt
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_yc_jnibase_JniClient_JavaCallCForInt
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
