/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_car_rclinkservice_jni_CarLinkJni */

#ifndef _Included_com_car_rclinkservice_jni_CarLinkJni
#define _Included_com_car_rclinkservice_jni_CarLinkJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_car_rclinkservice_jni_CarLinkJni
 * Method:    CARCInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_car_rclinkservice_jni_CarLinkJni_CARCInit
  (JNIEnv *, jclass);

/*
 * Class:     com_car_rclinkservice_jni_CarLinkJni
 * Method:    CARC5msTask
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_car_rclinkservice_jni_CarLinkJni_CARC5msTask
  (JNIEnv *, jclass);

/*
 * Class:     com_car_rclinkservice_jni_CarLinkJni
 * Method:    CARC10msTask
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_car_rclinkservice_jni_CarLinkJni_CARC10msTask
  (JNIEnv *, jclass);

/*
 * Class:     com_car_rclinkservice_jni_CarLinkJni
 * Method:    setRadioBytes
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_car_rclinkservice_jni_CarLinkJni_setRadioBytes
  (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
