/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndkbase_NDKClient */

#ifndef _Included_com_example_ndkbase_NDKClient
#define _Included_com_example_ndkbase_NDKClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndkbase_NDKClient
 * Method:    HelloJni
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ndkbase_NDKClient_HelloJni
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_example_ndkbase_NDKClient
 * Method:    LoadID3
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndkbase_NDKClient_LoadID3
  (JNIEnv *, jclass);

/*
 * Class:     com_example_ndkbase_NDKClient
 * Method:    SetFilePath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_ndkbase_NDKClient_SetFilePath
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_ndkbase_NDKClient
 * Method:    GetID3Title
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ndkbase_NDKClient_GetID3Title
  (JNIEnv *, jclass);

/*
 * Class:     com_example_ndkbase_NDKClient
 * Method:    ReleaseID3
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndkbase_NDKClient_ReleaseID3
  (JNIEnv *, jclass);

/*
 * Class:     com_example_ndkbase_NDKClient
 * Method:    callJavaStaticMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndkbase_NDKClient_callJavaStaticMethod
  (JNIEnv *, jclass);

/*
 * Class:     com_example_ndkbase_NDKClient
 * Method:    callJavaInstanceMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndkbase_NDKClient_callJavaInstanceMethod
  (JNIEnv *, jclass);

/*
 * Class:     com_example_ndkbase_NDKClient
 * Method:    accessStaticField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndkbase_NDKClient_accessStaticField
  (JNIEnv *, jclass);

/*
 * Class:     com_example_ndkbase_NDKClient
 * Method:    accessInstanceField
 * Signature: (Lcom/example/ndkbase/JavaMethod;)V
 */
JNIEXPORT void JNICALL Java_com_example_ndkbase_NDKClient_accessInstanceField
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_example_ndkbase_NDKClient
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndkbase_NDKClient_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     com_example_ndkbase_NDKClient
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndkbase_NDKClient_nativeMethod
  (JNIEnv *, jclass);

/*
 * Class:     com_example_ndkbase_NDKClient
 * Method:    exceptionMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndkbase_NDKClient_exceptionMethod
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
